version: "3.7"
services:
  postgres:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - 5434:5432
    volumes:
      - /db:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: fastify.Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
